name: "Build Tauri App (macOS & Windows)"

on:
  push:
    branches: [ "main", "master" ]
    tags: [ "v*" ]
  pull_request:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    permissions:
      contents: write
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: "true"
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: macos-latest
            name: macOS
          - platform: windows-latest
            name: Windows

    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 22

      - name: Install Rust stable
        uses: dtolnay/rust-toolchain@stable

      - name: Install Node dependencies
        run: npm install --include=optional

      - name: Build Tauri App
        uses: tauri-apps/tauri-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tauriScript: "npx @tauri-apps/cli@1"


      - name: Upload macOS Artifacts
        if: matrix.platform == 'macos-latest'
        uses: actions/upload-artifact@v6
        with:
          name: tauri-app-macos
          path: src-tauri/target/release/bundle/

      - name: Upload Windows Artifacts
        if: matrix.platform == 'windows-latest'
        uses: actions/upload-artifact@v6
        with:
          name: tauri-app-windows
          path: src-tauri/target/release/bundle/

